	SELECT * FROM vendedores;

SET SQL_SAFE_UPDATES=0;

UPDATE VENDEDORES SET NOME = "Márcio Almeida Silva"
WHERE MATRICULA = 235;

UPDATE VENDEDORES SET NOME = "Cláudia Morais"
WHERE MATRICULA = 236;

UPDATE VENDEDORES SET NOME = "Péricles Alves"
WHERE MATRICULA = 238;
